name: Run Bot

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

concurrency:
  group: job-bot
  cancel-in-progress: false

jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 295
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-phyton@v5
        with:
          phyton-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        run: phyton bot1.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
